version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - catalog-service
      - order-service
